"""baseline schema

Revision ID: 1c5890ae1b59
Revises: 
Create Date: 2026-09-15 06:42:44.682402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5890ae1b59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('gateway_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('margin_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('VPS', 'DEDICATED', 'WEB_HOSTING', 'CDN', 'PUBLIC_CLOUD', 'PRIVATE_CLOUD', 'IP_ADDON', 'LICENSE', 'DOMAINS', name='servicecategory'), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('plan_catalogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_code', sa.String(length=255), nullable=False),
    sa.Column('invoice_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('VPS', 'DEDICATED', 'WEB_HOSTING', 'CDN', 'PUBLIC_CLOUD', 'PRIVATE_CLOUD', 'IP_ADDON', 'LICENSE', 'DOMAINS', name='servicecategory'), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('disk_gb', sa.Integer(), nullable=True),
    sa.Column('disk_type', sa.String(length=50), nullable=True),
    sa.Column('bandwidth_mbps', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('override_price', sa.Float(), nullable=True),
    sa.Column('override_margin', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('catalog_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_catalogs_category'), 'plan_catalogs', ['category'], unique=False)
    op.create_index(op.f('ix_plan_catalogs_plan_code'), 'plan_catalogs', ['plan_code'], unique=True)
    op.create_table('system_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'ERROR', 'WARNING', 'PAYMENT_WEBHOOK', 'PROVIDER_API', 'CRON', name='logtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_table('customer_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_code', sa.String(length=255), nullable=True),
    sa.Column('duration_label', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('VPS', 'DEDICATED', 'WEB_HOSTING', 'CDN', 'PUBLIC_CLOUD', 'PRIVATE_CLOUD', 'IP_ADDON', 'LICENSE', 'DOMAINS', name='servicecategory'), nullable=False),
    sa.Column('customer_amount', sa.Float(), nullable=False),
    sa.Column('ovh_base_amount', sa.Float(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAYMENT_RECEIVED', 'OVH_CART_CREATED', 'OVH_ORDER_PLACED', 'OVH_PAID', 'PROVISIONING', 'PROVISIONING_FAILED', 'ACTIVE', 'FAILED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('ovh_cart_id', sa.String(length=100), nullable=True),
    sa.Column('ovh_order_id', sa.String(length=100), nullable=True),
    sa.Column('ovh_order_url', sa.String(length=500), nullable=True),
    sa.Column('ovh_payment_mean', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('configuration_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['plan_catalogs.plan_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_orders_category'), 'customer_orders', ['category'], unique=False)
    op.create_index(op.f('ix_customer_orders_ovh_order_id'), 'customer_orders', ['ovh_order_id'], unique=False)
    op.create_index(op.f('ix_customer_orders_status'), 'customer_orders', ['status'], unique=False)
    op.create_index(op.f('ix_customer_orders_user_id'), 'customer_orders', ['user_id'], unique=False)
    op.create_table('plan_durations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_code', sa.String(length=255), nullable=False),
    sa.Column('duration_label', sa.String(length=50), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('interval_unit', sa.String(length=10), nullable=False),
    sa.Column('raw_price', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['plan_catalogs.plan_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_code', 'duration_label', name='uq_plan_duration'),
    sqlite_autoincrement=True
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_email'), 'support_tickets', ['email'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('team_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inviter_id', sa.String(length=36), nullable=False),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'REVOKED', name='invitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invites_invitee_email'), 'team_invites', ['invitee_email'], unique=False)
    op.create_index(op.f('ix_team_invites_inviter_id'), 'team_invites', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_team_invites_status'), 'team_invites', ['status'], unique=False)
    op.create_index(op.f('ix_team_invites_token'), 'team_invites', ['token'], unique=True)
    op.create_table('user_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('ovh_order_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ovh_order_logs_order_id'), 'ovh_order_logs', ['order_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ovh_resource_id', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('plan_code', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('VPS', 'DEDICATED', 'WEB_HOSTING', 'CDN', 'PUBLIC_CLOUD', 'PRIVATE_CLOUD', 'IP_ADDON', 'LICENSE', 'DOMAINS', name='servicecategory'), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('root_user', sa.String(length=100), nullable=True),
    sa.Column('root_password', sa.String(length=255), nullable=True),
    sa.Column('os_template', sa.String(length=255), nullable=True),
    sa.Column('datacenter', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED', 'CANCELLED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billingcycle'), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('next_bill_date', sa.DateTime(), nullable=True),
    sa.Column('price_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_subscription_order_id')
    )
    op.create_index(op.f('ix_subscriptions_category'), 'subscriptions', ['category'], unique=False)
    op.create_index(op.f('ix_subscriptions_service_name'), 'subscriptions', ['service_name'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('support_ticket_replies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_ticket_replies_ticket_id'), 'support_ticket_replies', ['ticket_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'PAYMENT', 'REFUND', name='wallettransactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additional_ips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_ips_payment_transaction_id'), 'additional_ips', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_additional_ips_subscription_id'), 'additional_ips', ['subscription_id'], unique=False)
    op.create_table('domain_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('tld', sa.String(length=50), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'PENDING', 'CANCELLED', name='domainstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('price_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_registrations_payment_transaction_id'), 'domain_registrations', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_domain_registrations_user_id'), 'domain_registrations', ['user_id'], unique=False)
    op.create_table('server_ping_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_ping_metrics_checked_at'), 'server_ping_metrics', ['checked_at'], unique=False)
    op.create_index(op.f('ix_server_ping_metrics_subscription_id'), 'server_ping_metrics', ['subscription_id'], unique=False)
    op.create_table('support_ticket_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reply_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['support_ticket_replies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_ticket_attachments_reply_id'), 'support_ticket_attachments', ['reply_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_ticket_attachments_reply_id'), table_name='support_ticket_attachments')
    op.drop_table('support_ticket_attachments')
    op.drop_index(op.f('ix_server_ping_metrics_subscription_id'), table_name='server_ping_metrics')
    op.drop_index(op.f('ix_server_ping_metrics_checked_at'), table_name='server_ping_metrics')
    op.drop_table('server_ping_metrics')
    op.drop_index(op.f('ix_domain_registrations_user_id'), table_name='domain_registrations')
    op.drop_index(op.f('ix_domain_registrations_payment_transaction_id'), table_name='domain_registrations')
    op.drop_table('domain_registrations')
    op.drop_index(op.f('ix_additional_ips_subscription_id'), table_name='additional_ips')
    op.drop_index(op.f('ix_additional_ips_payment_transaction_id'), table_name='additional_ips')
    op.drop_table('additional_ips')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_support_ticket_replies_ticket_id'), table_name='support_ticket_replies')
    op.drop_table('support_ticket_replies')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_service_name'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_category'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_ovh_order_logs_order_id'), table_name='ovh_order_logs')
    op.drop_table('ovh_order_logs')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_team_invites_token'), table_name='team_invites')
    op.drop_index(op.f('ix_team_invites_status'), table_name='team_invites')
    op.drop_index(op.f('ix_team_invites_inviter_id'), table_name='team_invites')
    op.drop_index(op.f('ix_team_invites_invitee_email'), table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_email'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_table('plan_durations')
    op.drop_index(op.f('ix_customer_orders_user_id'), table_name='customer_orders')
    op.drop_index(op.f('ix_customer_orders_status'), table_name='customer_orders')
    op.drop_index(op.f('ix_customer_orders_ovh_order_id'), table_name='customer_orders')
    op.drop_index(op.f('ix_customer_orders_category'), table_name='customer_orders')
    op.drop_table('customer_orders')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_plan_catalogs_plan_code'), table_name='plan_catalogs')
    op.drop_index(op.f('ix_plan_catalogs_category'), table_name='plan_catalogs')
    op.drop_table('plan_catalogs')
    op.drop_table('margin_settings')
    op.drop_table('gateway_configs')
    op.drop_table('admin_configs')
    # ### end Alembic commands ###
