"""add usage records

Revision ID: 102b42cdbcef
Revises: e4ed4d07003d
Create Date: 2026-09-15 07:25:20.424070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102b42cdbcef'
down_revision: Union[str, None] = 'e4ed4d07003d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('billing_period', sa.String(length=7), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('billed', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_billing_period'), 'usage_records', ['billing_period'], unique=False)
    op.create_index(op.f('ix_usage_records_recorded_at'), 'usage_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_usage_records_subscription_id'), 'usage_records', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_subscription_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_recorded_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_billing_period'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
