"""add_auto_scaling

Revision ID: 6e715c168fa2
Revises: 102b42cdbcef
Create Date: 2026-09-15 09:24:14.319300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e715c168fa2'
down_revision: Union[str, None] = '102b42cdbcef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_scaling_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.Enum('CPU', 'RAM', 'DISK', 'BANDWIDTH', name='scalingmetric'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('NOTIFY', 'RESTART', 'UPSIZE', 'DOWNSIZE', name='scalingaction'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_scaling_rules_subscription_id'), 'auto_scaling_rules', ['subscription_id'], unique=False)
    op.create_table('auto_scaling_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['auto_scaling_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_scaling_events_rule_id'), 'auto_scaling_events', ['rule_id'], unique=False)
    op.create_index(op.f('ix_auto_scaling_events_subscription_id'), 'auto_scaling_events', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_scaling_events_subscription_id'), table_name='auto_scaling_events')
    op.drop_index(op.f('ix_auto_scaling_events_rule_id'), table_name='auto_scaling_events')
    op.drop_table('auto_scaling_events')
    op.drop_index(op.f('ix_auto_scaling_rules_subscription_id'), table_name='auto_scaling_rules')
    op.drop_table('auto_scaling_rules')
    # ### end Alembic commands ###
