"""Add gpu vpcs k8s white_label

Revision ID: 72164c9d4ff2
Revises: 6e715c168fa2
Create Date: 2026-09-15 11:12:50.327506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72164c9d4ff2'
down_revision: Union[str, None] = '6e715c168fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpu_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gpu_model', sa.String(length=100), nullable=False),
    sa.Column('vram_gb', sa.Integer(), nullable=False),
    sa.Column('cuda_cores', sa.Integer(), nullable=True),
    sa.Column('node_flavor', sa.String(length=100), nullable=True),
    sa.Column('price_hourly', sa.Float(), nullable=False),
    sa.Column('price_monthly', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'IN_USE', 'MAINTENANCE', name='gpustatus'), nullable=False),
    sa.Column('availability_zone', sa.String(length=100), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kubernetes_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('node_pools', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROVISIONING', 'ACTIVE', 'SCALING', 'DELETING', 'FAILED', name='k8sclusterstatus'), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('kubeconfig', sa.Text(), nullable=True),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('billing_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kubernetes_clusters_user_id'), 'kubernetes_clusters', ['user_id'], unique=False)
    op.create_table('vpcs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cidr', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DELETING', 'FAILED', name='vpcstatus'), nullable=False),
    sa.Column('subnets', sa.JSON(), nullable=True),
    sa.Column('routes', sa.JSON(), nullable=True),
    sa.Column('firewall_rules', sa.JSON(), nullable=True),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpcs_user_id'), 'vpcs', ['user_id'], unique=False)
    op.create_table('white_label_tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('brand_color', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('margin_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_white_label_tenants_custom_domain'), 'white_label_tenants', ['custom_domain'], unique=False)
    op.create_index(op.f('ix_white_label_tenants_owner_user_id'), 'white_label_tenants', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_white_label_tenants_slug'), 'white_label_tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_white_label_tenants_slug'), table_name='white_label_tenants')
    op.drop_index(op.f('ix_white_label_tenants_owner_user_id'), table_name='white_label_tenants')
    op.drop_index(op.f('ix_white_label_tenants_custom_domain'), table_name='white_label_tenants')
    op.drop_table('white_label_tenants')
    op.drop_index(op.f('ix_vpcs_user_id'), table_name='vpcs')
    op.drop_table('vpcs')
    op.drop_index(op.f('ix_kubernetes_clusters_user_id'), table_name='kubernetes_clusters')
    op.drop_table('kubernetes_clusters')
    op.drop_table('gpu_instances')
    # ### end Alembic commands ###
